/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;


import dominio.*;
import dominio.Sistema;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gonza
 */
public class HistorialPostulante extends javax.swing.JFrame {

    private Sistema miSistema;
    
    DefaultListModel<Postulante> modelo;
    
    public HistorialPostulante(Sistema sistema) {
       miSistema = sistema;
       initComponents();
       modelo = new DefaultListModel<>();
       ListaPostulantes.setModel(modelo);
       actualizarLista();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPostulantes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelCedula = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        LabelMail = new javax.swing.JLabel();
        LabelLinkedin = new javax.swing.JLabel();
        LabelExperiencia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaExperiencias = new javax.swing.JList<>();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        LabelBuscar = new javax.swing.JLabel();
        BotonBorrar = new javax.swing.JButton();
        BotonResetar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaValores = new javax.swing.JTable();
        BotonSalir = new javax.swing.JButton();
        TextBuscador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Historial postulante");

        ListaPostulantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaPostulantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPostulantes);

        jLabel1.setText("Postulantes:");

        LabelNombre.setText("Nombre:");

        LabelCedula.setText("Cédula:");

        LabelDireccion.setText("Dirección:");

        LabelTelefono.setText("Telefono:");

        LabelMail.setText("Mail:");

        LabelLinkedin.setText("Linkedin:");

        LabelExperiencia.setText("Experiencia:");

        jScrollPane2.setViewportView(ListaExperiencias);

        label2.setText("label2");

        label3.setText("label3");

        label4.setText("label4");

        label5.setText("label5");

        label6.setText("label6");

        label7.setText("label7");

        LabelBuscar.setText("Buscar: ");

        BotonBorrar.setText("Borrar");

        BotonResetar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonResetar.setText("Resetear");
        BotonResetar.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));

        TablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Evaluador", "Puntaje", "Comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaValores.setPreferredSize(new java.awt.Dimension(200, 80));
        jScrollPane3.setViewportView(TablaValores);

        BotonSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelNombre)
                                            .addComponent(LabelCedula)
                                            .addComponent(LabelDireccion)
                                            .addComponent(LabelTelefono)
                                            .addComponent(LabelMail)
                                            .addComponent(LabelLinkedin)
                                            .addComponent(LabelExperiencia))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelBuscar)
                                .addGap(61, 61, 61)
                                .addComponent(TextBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonResetar))))
                    .addComponent(BotonSalir)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNombre)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCedula)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelDireccion)
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(LabelTelefono)
                                                        .addGap(10, 10, 10)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(LabelMail)
                                                                .addGap(14, 14, 14)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(LabelLinkedin)
                                                                        .addGap(10, 10, 10)
                                                                        .addComponent(LabelExperiencia))))
                                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonBorrar)
                        .addComponent(TextBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonResetar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LabelBuscar)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        label2.getAccessibleContext().setAccessibleParent(LabelNombre);
        label3.getAccessibleContext().setAccessibleParent(LabelCedula);
        label4.getAccessibleContext().setAccessibleParent(LabelDireccion);
        label5.getAccessibleContext().setAccessibleParent(LabelTelefono);
        label6.getAccessibleContext().setAccessibleParent(LabelMail);
        label7.getAccessibleContext().setAccessibleParent(LabelLinkedin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaPostulantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaPostulantesValueChanged
        Postulante postulanteSelected = ListaPostulantes.getSelectedValue();
        limpiarLabels();
        actualizarListaExperiencias(postulanteSelected);
        String nombre=postulanteSelected.getNombre();
        String cedula=postulanteSelected.getCedula();
        String direccion=postulanteSelected.getDireccion();
        String telefono=postulanteSelected.getTelefono();
        String mail=postulanteSelected.getEmail();
        String linkedin=   postulanteSelected.getLinkedin();
        LabelNombre.setText(nombre);
        LabelCedula.setText(cedula);
        LabelDireccion.setText(direccion);
        LabelTelefono.setText(telefono);
        LabelMail.setText(mail);
        LabelLinkedin.setText(linkedin);
        
    }//GEN-LAST:event_ListaPostulantesValueChanged
     public void actualizarLista(){
     DefaultListModel<Postulante> modeloL = new DefaultListModel<>();
     ArrayList<Postulante> postulantes = miSistema.obtenerListaPostulantes();
     for (Postulante j: postulantes) {
        modeloL.addElement(j);
    }
    ListaPostulantes.setModel(modeloL);
    }
    public void actualizarListaExperiencias(Postulante postulante){
     DefaultListModel<String> modeloLE = new DefaultListModel<>();
     Map<Habilidad, Integer> habilidades = postulante.getHabilidades();
       for (Map.Entry<Habilidad, Integer> entry : habilidades.entrySet()) {
            modeloLE.addElement(entry.getKey() + " (" + entry.getValue()+")");
        }
    ListaExperiencias.setModel(modeloLE);   
    
    }
    public void limpiarLabels(){
    LabelCedula.setText("");
    LabelDireccion.setText("");
    LabelExperiencia.setText("");
    LabelLinkedin.setText("");
    LabelMail.setText("");
    LabelNombre.setText("");
    LabelTelefono.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonResetar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelCedula;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelExperiencia;
    private javax.swing.JLabel LabelLinkedin;
    private javax.swing.JLabel LabelMail;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JList<String> ListaExperiencias;
    private javax.swing.JList<Postulante
    > ListaPostulantes;
    private javax.swing.JTable TablaValores;
    private javax.swing.JTextField TextBuscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}

